config/routes.rb
Rubymon::Application.routes.draw do

  root 'welcome#index'
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  
  # Global Resources
  resources :users do
    resources :monsters
  end
  
end

app/models/monster.rb
# == Schema Information
#
# Table name: monsters
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  power           :string(255)
#  user_id         :integer
#  monster_type_id :integer
#  team_id         :integer
#  created_at      :datetime
#  updated_at      :datetime
#

class Monster < ActiveRecord::Base
  
  #associations
  belongs_to :team
  belongs_to :user
  belongs_to :monster_type
  
  #validations
  validates :name, presence: true
  validate :user_monsters_cannot_be_past_twenty, :monsters_cannot_be_past_three_in_a_team
  
  accepts_nested_attributes_for :team
  
  def as_json(options={})
    { "name" => name,
      "type" => monster_type.name,
      "power" => power,
      "team" => team.name}
  end
  
  def self.sort(monsters, params)
    unless params[:sort] == "weakness"
      params[:sort] ||= "name"
      monsters.order("#{params[:sort]} ASC")
    else
      monsters.joins([:monster_type => :weakness]).order("monster_types.name ASC")
    end
  end
  
  private
    def user_monsters_cannot_be_past_twenty
      if user.monsters.count >= 20
        errors.add(:user_id, "can't be same for more than twenty monsters")
      end
    end
    
    def monsters_cannot_be_past_three_in_a_team
      if team.monsters.count >= 3
        errors.add(:team_id, "cam hold maximum of three monsters")
      end
    end
end

app/models/monster_type.rb
# == Schema Information
#
# Table name: monster_types
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  strength_id :integer
#  weakness_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class MonsterType < ActiveRecord::Base
  
  #associations
  has_one :strength, class_name: "MonsterType", foreign_key: "strength_id"
  has_one :weakness, class_name: "MonsterType", foreign_key: "weakness_id"
  
  def self.seed
    fire = MonsterType.create(name: "fire")
    water = MonsterType.create(name: "water")
    earth = MonsterType.create(name: "earth")
    electric = MonsterType.create(name: "electric")
    wind = MonsterType.create(name: "wind")
    
    fire.update_attributes(strength_id: wind.id, weakness_id: water.id)
    water.update_attributes(strength_id: fire.id, weakness_id: earth.id)
    earth.update_attributes(strength_id: water.id, weakness_id: electric.id)
    electric.update_attributes(strength_id: earth.id, weakness_id: wind.id)
    wind.update_attributes(strength_id: electric.id, weakness_id: fire.id)
  end
end

app/models/team.rb
# == Schema Information
#
# Table name: teams
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Team < ActiveRecord::Base

  #associations
  has_many :monsters
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  uid                    :string(255)
#  provider               :string(255)
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  #associtions
  has_many :monsters
  
  #omniauth related methods
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
    end
  end
  
  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  
  before_filter :get_user, except: [:update, :destroy]
  before_filter :get_monster, except: [:index, :new, :create]
  
  def index
    respond_to do |format|
      format.html{ render :json => @user.monsters.as_json }
      format.json{ render :json => @user.monsters.as_json }
    end
  end
  
  def new
    @monster = @user.monsters.build
  end
  
  def create
    monster = @user.monsters.new(monster_params)
    if monster.save
      respond_to do |format|
        format.html{ render :json => monster.as_json }
        format.json{ render :json => monster.as_json }
      end
    else
      render json: "Monster not created - #{monster.errors.full_messages.join(', ')}".to_json
    end
  end

  def edit
  end
  
  def update
    if @monster.update(monster_params)
      respond_to do |format|
        format.html{ render :json => @monster.reload.as_json }
        format.json{ render :json => @monster.reload.as_json }
      end
    else
      render json: "Monster not updated - #{@monster.errors.full_messages.join(', ')}".to_json
    end
  end
  
  def destroy
    @monster.delete
    respond_to do |format|
      format.html{ render :json => @monster.as_json }
      format.json{ render :json => @monster.as_json }
    end
  end
  
  private
  
    def monster_params
      params.require(:monster).permit(:name, :power, :monster_type_id, :team_attributes => [:name])
    end
    
    def get_user
      @user = User.find params[:user_id]
    end
    
    def get_monster
      @monster = Monster.find params[:id]
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    if request.env["omniauth.auth"].info.email.blank?
      redirect_to "/users/auth/facebook?auth_type=rerequest&scope=email"
    end
    
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = current_user
    @monsters = Monster.sort(@user.monsters, params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rubymon</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" id="flash">
        <button aria-hidden="true" class="close" data-dismiss="alert" type="button">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>
  <div class="col-md-12 ">
  <div class="pull-right">
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' if user_signed_in? %>
  </div>
  <%= yield %>
</body>
</html>

app/views/monsters/_form.html.erb
<%= form_for([@user, @monster]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name%>
  </p>

  <p>
    <%= f.label :power %><br>
    <%= f.text_field :power %>
  </p>
  
  <p>
    <%= f.fields_for :team_attributes do |team| %>
      <%= team.label :name, "Team" %><br>
      <%= team.text_field :name, value: @monster.team.try(:name) %>
    <%end%>
  </p>
  
  <p>
    <%= f.label :type %><br>
    <%= f.select :monster_type_id, options_for_select(MonsterType.all.map{|m| [m.name.titleize, m.id]}) %>
  </p>
  
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', root_path %>

app/views/monsters/edit.html.erb
<h2>Edit monster</h2>
<%= render partial: "monsters/form"%>

app/views/monsters/new.html.erb
<h2>Create monster</h2>
<%= render partial: "monsters/form"%>

app/views/welcome/index.html.erb
<h2>Welcome <i><%= @user.email %>!</i></h2>
<br>
<%= link_to '+ New Monster', new_user_monster_path(@user) if @monsters.count < 20%>
 <% if @monsters.any? %>
  <h3>Your Monsters:</h3>
   Sort By: <%= link_to 'Name', root_path(sort: "name") %> |
          <%= link_to 'Power', root_path(sort: "power") %> |
          <%= link_to 'Weakness', root_path(sort: "weakness") %>
  <hr>
  <% @monsters.each do |monster| %>
    <p>
      <strong>Name:</strong>
      <%= monster.name %>
    </p>
   
    <p>
      <strong>Type:</strong>
      <%= monster.monster_type.name.titleize%>
    </p>
    
    <p>
      <strong>Power:</strong>
      <%= monster.power%>
    </p>
    
    <p>
      <strong>Team: </strong>
      <%= monster.team.name %>
    </p>
    <%= link_to 'Edit', edit_user_monster_path(@user, monster) %> |
    <%= link_to 'Delete', user_monster_path(@user, monster), :method=>'delete' %>
    <hr><br>
  <% end %>
<% end %>